{"status_code":15,"lang":"python3","run_success":false,"runtime_error":"Line 63: TypeError: <__main__.TreeNode object at 0x7fb8b6365650> is not valid value for the expected return type TreeNode","full_runtime_error":"TypeError: <__main__.TreeNode object at 0x7fb8b6365650> is not valid value for the expected return type TreeNode\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    raise TypeError(str(ret) + \" is not valid value for the expected return type TreeNode\");\nLine 63 in _driver (Solution.py)\n    _driver()\nLine 72 in <module> (Solution.py)\nDuring handling of the above exception, another exception occurred:\nException: Type <class '__main__.TreeNode'> cannot be serialized\nLine 138 in serializer_node (./python3/__serializer__.py)\nLine 181 in _serialize_default (./python3/__serializer__.py)\nLine 200 in _serialize (./python3/__serializer__.py)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    out = ser._serialize(ret, 'TreeNode')\nLine 61 in _driver (Solution.py)","status_runtime":"N/A","memory":17348000,"question_id":"1050","elapsed_time":117,"compare_result":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","code_output":"","std_output":"","last_testcase":"[8,5,1,7,10,12]","expected_output":"[8,5,10,1,7,null,12]","task_finish_time":1733713694455,"task_name":"judger.judgetask.Judge","finished":true,"total_correct":0,"total_testcases":111,"runtime_percentile":null,"status_memory":"N/A","memory_percentile":null,"pretty_lang":"Python3","submission_id":"1473952463","status_msg":"Runtime Error","state":"SUCCESS"}